### ISSUE TITLE
getEntityTypes is not working

### ISSUE THREAD

**Issue by dhruvrajkotia** [googleapis/nodejs-dialogflow-cx#169]
```
'use strict';
const path = require("path");

async function main() {
const projectId = '****';
const location = '****';
const languageCode= 'de';
const agentId = '****';
const entityTypeID = '****'

const {EntityTypesClient} = require('@google-cloud/dialogflow-cx');
  const client = new EntityTypesClient({apiEndpoint: 'us-central1-dialogflow.googleapis.com'});

  async function getEntity() {
    const parent = client.entityTypePath(projectId, location, agentId, entityTypeID);
    console.info(parent);
    const [entity] = await client.getEntityType({
      parent,
      pageSize: 100,
      languageCode: languageCode
    });
    entity.forEach(entity => {
      console.log('====================');
      console.log(`Entity name: ${JSON.stringify(entity)}`);
    });
  }

  getEntity();
}
```

Above program give result in the Invalid Argument and if we try with the **listEntityTypes** then it's works fine. So Probably some issue with the getEntityType method. 

Program Result: 
`3 INVALID_ARGUMENT: Resource name '' does not match 'projects/*/locations/*/agents/*/entityTypes/*'.`

Let me know if you need any more information. 

Thanks

**Comment by b-loved-dreamer** [comment]
Hi @dhruvrajkotia. You can fetch a single ```EntityType``` by making the following updates to your code:

```
  const getEntityTypeRequest = {
    name: parent,
    languageCode: languageCode,
  };

  const [resultEntity] = await client.getEntityType(getEntityTypeRequest);

  resultEntity.entities.forEach(entity => {
    console.log('====================');
    console.log(`Entity name: ${JSON.stringify(entity.synonyms)}`);
  });
```

Your request object only takes a ```name``` (the resource name) and a ```language_code```, as indicated in the [documentation](https://cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.dialogflow.cx.v3#google.cloud.dialogflow.cx.v3.GetEntityTypeRequest). Additionally, you might have to change you endpoint to "dialogflow.googleapis.com".

**Comment by telpirion** [comment]
It looks like this issue has been resolved. @dhruvrajkotia please feel free to reopen if @b-loved-dreamer 's answer doesn't address your concern.
