### ISSUE TITLE
Errors in Create-agent sample

### ISSUE THREAD

**Issue by rnsloanwool** [googleapis/nodejs-dialogflow-cx#175]
https://github.com/googleapis/nodejs-dialogflow-cx/blob/main/samples/create-agent.js

1. `api_endpoint` is not the correct property name for the Javascript library:  https://github.com/googleapis/nodejs-dialogflow-cx/blob/main/samples/create-agent.js
2. `global-dialogflow.googleapis.com:443` is the port number necessary? Here is a code sample using the `PagesClient` that shows when including the port number can cause problems:

```
const { PagesClient } = require("@google-cloud/dialogflow-cx");

async function main() {
  try {
    const projectId = 'xxxx';
    const location = "australia-southeast1";
    const agentId = "xxxx";
    const flowId = "xxxx";
    const apiEndpoint = "australia-southeast1-dialogflow.googleapis.com:443";
    const pageName = "test-page";

    const pagesClient = new PagesClient({ apiEndpoint });
    const createPageRequest = {
      parent:
        `projects/${projectId}/locations/${location}/agents/${agentId}/flows/${flowId}`,
      page: {
        displayName: pageName,
      },
    };

    const response = await pagesClient.createPage(createPageRequest);
    console.log(response);    
  } catch (e) {
    console.error(e);
  }
}

main();
```

The request above will fail silently when attempting to create the page. Removing `:443` from API endpoint fixes the problem.

#### Environment details

  - OS: OS X
  - Node.js version: 12.18.3
  - npm version: 6.14.6
  - `@google-cloud/dialogflow-cx` version: 2.13.0

**Comment by galz10** [comment]
Fixed #182
