### ISSUE TITLE
`StreamingDetectIntent` doesn't process audio after matching first intent

### ISSUE THREAD

**Issue by nishantt95** [googleapis/nodejs-dialogflow-cx#178]
#### Environment details

  - OS: Windows 10, 11. Debian 9 (stretch)
  - Node.js version: 12.18.3, 12.22.1
  - npm version: 7.19.0, 7.15.0
  - `@google-cloud/dialogflow-cx` version: 2.13.0

#### Issue
`StreamingDetectIntent` doesn't process audio after matching the first intent. I am able to see the transcription and it is able to match the first intent but after matching the first intent, the audio keeps on streaming but I receive no transcription, and `on('data')` callback is also not triggered. _In short, nothing happens after matching the first intent_

![image](https://user-images.githubusercontent.com/9738956/133778588-46e657a0-9532-4566-8d83-c15c43e1ddbf.png)

**One thing that worked around it was that I've to end the `detectStream` and then reinitialize it. Then it worked as expected.**

#### Steps to reproduce
I've tried with `const {SessionsClient} = require("@google-cloud/dialogflow-cx");` and 
`const {SessionsClient} = require("@google-cloud/dialogflow-cx").v3;`

```javascript
// Create a stream for the streaming request.
const detectStream = client
    .streamingDetectIntent()
    .on('error', console.error)
    .on('end', (data)=>{
        console.log(`streamingDetectIntent: -----End-----: ${JSON.stringify(data)}`);
    })
    .on('data', data => {
        console.log(`streamingDetectIntent: Data: ----------`);
        if (data.recognitionResult) {
            console.log(`Intermediate Transcript: ${data.recognitionResult.transcript}`);
        } else {
            console.log('Detected Intent:');
            if(!data.detectIntentResponse) return
            const result = data.detectIntentResponse.queryResult;

            console.log(`User Query: ${result.transcript}`);
            for (const message of result.responseMessages) {
                if (message.text) {
                    console.log(`Agent Response: ${message.text.text}`);
                }
            }
            if (result.match.intent) {
                console.log(`Matched Intent: ${result.match.intent.displayName}`);
            }
            console.log(`Current Page: ${result.currentPage.displayName}`);
        }
    });

const initialStreamRequest = {
        session: sessionPath,
        queryInput: {
            audio: {
                config: {
                    audioEncoding: encoding,
                    sampleRateHertz: sampleRateHertz,
                    singleUtterance: true,
                },
            },
            languageCode: languageCode,
        }
    };
detectStream.write(initialStreamRequest);

```

I've tried streaming audio via files (.wav) & using the microphone but resulted in the same behavior.

```javascript
await pump(
        recordingStream, // microphone stream <OR> fs.createReadStream(audioFileName),
        // Format the audio stream into the request format.
        new Transform({
            objectMode: true,
            transform: (obj, _, next) => {
                next(null, {queryInput: {audio: {audio: obj}}});
            },
        }),
        detectStream
    );
```

I've referred to this [implementation](https://github.com/googleapis/nodejs-dialogflow-cx/blob/main/samples/detect-intent-streaming.js) and this [rpc based doc](https://cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.dialogflow.cx.v3) as well but couldn't found any reason as to why this should not work.

Thanks!

**Comment by b-loved-dreamer** [comment]
Hi @nishantt95 — thank you for filing this issue. I believe that's the correct behavior for all ```streaming``` flavors of our services. Check out [this](https://github.com/googleapis/nodejs-speech/blob/88df0763de1021c915c2b843766397253243058e/samples/infiniteStreaming.js#L194) for an example on how to handle restarting the stream.

**Comment by nishantt95** [comment]
> Hi @nishantt95 — thank you for filing this issue. I believe that's the correct behavior for all `streaming` flavors of our services. Check out [this](https://github.com/googleapis/nodejs-speech/blob/88df0763de1021c915c2b843766397253243058e/samples/infiniteStreaming.js#L194) for an example on how to handle restarting the stream.

Got it, Thanks! 👍
