### ISSUE TITLE
Cloud function's entry point shouldn't have the `exports.` prefix.

### ISSUE THREAD

**Issue by Slony** [googleapis/nodejs-dialogflow-cx#243]
1) Is this a client library issue or a product issue?
This is the Dialogflow CX web hook code sample for Cloud Functions, Node.js environment.

2) Did someone already solve this?
No.

3) Do you have a support contract?
I'm a customer engineer in Google Cloud.

#### Environment details

  - OS: Cloud Functions
  - Node.js version: any
  - npm version: n/a
  - `@google-cloud/dialogflow-cx` version: any

#### Steps to reproduce

  1. Create a Cloud Function using the [code snippet](https://cloud.google.com/dialogflow/cx/docs/concept/webhook#webhook-nodejs).
  2. Set entry point to `exports.handleWebhook` in the Cloud Function.
  3. The Cloud Function deploy fails with the following errors seen in Cloud Logging:
```
Function cannot be initialized. Error: function terminated. Recommended action: inspect logs for termination reason. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging

Could not load the function, shutting down.

Did you specify the correct target function to execute?

Function 'exports.handleWebhook' is not defined in the provided module.
```

**Comment by galz10** [comment]
Working on fix #248
