### ISSUE TITLE
No response when send a request

### ISSUE THREAD

**Issue by gildastema** [googleapis/nodejs-dialogflow-cx#29]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-dialogflow-cx/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Debian 10
  - Node.js version: 14
  - npm version:
  - `@google-cloud/dialogflow-cx` version: 1.1.0

#### Steps to reproduce

  1.  send request a 
![Screen Capture_select-area_20201112235940](https://user-images.githubusercontent.com/19803232/99006697-29d82600-2543-11eb-976d-e072837c1037.png)

  2. no response  in my terminal

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
@gildastema mind sharing a gist of the code in your screen-shot?

**Comment by KuroInkH** [comment]
hey, did you solve it? I need help with deploying on dialogflow cx

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
