### ISSUE TITLE
Custom payload unreadable structure

### ISSUE THREAD

**Issue by Daners** [googleapis/nodejs-dialogflow-cx#60]
Hello, I am creating a small project, where I have found the following situation.
I'm using:
  - Nodejs: 12.20.0
  - google-cloud / dialogflow-cx: 2.2.0

I have a custom payload configured within a page in the response, which has the following structure:

![image](https://user-images.githubusercontent.com/3009697/107272160-e93d5b00-6a12-11eb-9bf4-9162fe87df21.png)

When making a request to the Dialogflow CX API v3beta1, I get a correct and readable structure, however when I do it through the SDK I get an unreadable response with a lot of garbage information:

![image](https://user-images.githubusercontent.com/3009697/107272454-551fc380-6a13-11eb-972c-a673df039042.png)

This is a small fragment of the code where I get the response from the SDK.

```javascript
const {SessionsClient} = require('@google-cloud/dialogflow-cx');
const client = new SessionsClient({ 
  apiEndpoint: "us-central1-dialogflow.googleapis.com",
   keyFilename:"./auth.json" });
...
 const sessionid = req.params["sessionid"]
const sessionPath = client.projectLocationAgentSessionPath(
    "PROJECT_ID",
    "us-central1",
    "AGENT_ID",
    sessionid
      );
    const body =  req.body;
    body.session = sessionPath
    client.detectIntent(body).then((data)=>{
      const [response] = data;
      console.log(JSON.stringify(data));
      res.json(response.queryResult)
    })
```
Could you help me to know if I am omitting any configuration?

**Comment by b-loved-dreamer** [comment]
Hi @Daners, Nodejs returns a ```protobuf.Value```, which is a ```Struct``` datatype.  The behavior you're seeing is working as intended. Please take a look at [this](https://github.com/protobufjs/protobuf.js/pull/1495). Additionally, you might want to read the [docs](https://cloud.google.com/dialogflow/cx/docs/reference/rpc/google.cloud.dialogflow.cx.v3#google.cloud.dialogflow.cx.v3.QueryResult).

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided some clarifying details a week or more ago and never heard back from you. Please feel free to re-open this issue if you'd like.

**Comment by fosteman** [comment]
Hi there, I went through the links you shared here @b-loved-dreamer , couldn't figure it out. Hope it's not a burden to reopen the issue. 
I am utilizing [pb-util](https://github.com/callmehiphop/pb-util) and had had fatal errors to occur. Ultimately, can't decode custom payloads.
<img width="454" alt="Screen Shot 2021-03-29 at 5 03 09 PM" src="https://user-images.githubusercontent.com/32850517/112899835-a57cde80-90b0-11eb-909d-558fb5c7fffe.png">

Do I need to use protobuf's types and somehow recreate them and then run `toObject` ? I'm a neophyte in protobuff, any help is much appreciated!
