### ISSUE TITLE
Protobuff `toObject` does not convert `WebhookPayload` correctly

### ISSUE THREAD

**Issue by fosteman** [googleapis/nodejs-dialogflow-cx#86]
Hi there, I went through the links @b-loved-dreamer  shared in #60 , couldn't figure it out. Hope it's not a burden to reopen the issue. 
I am utilizing [pb-util](https://github.com/callmehiphop/pb-util) and had had fatal errors to occur. Ultimately, can't decode custom payloads.
<img width="454" alt="Screen Shot 2021-03-29 at 5 03 09 PM" src="https://user-images.githubusercontent.com/32850517/112899835-a57cde80-90b0-11eb-909d-558fb5c7fffe.png">

I've tried running `toObject` from the `QueryResult proto` and still getting protobuf values
<img width="607" alt="Screen Shot 2021-03-29 at 8 24 38 PM" src="https://user-images.githubusercontent.com/32850517/112915672-ca7f4a80-90cc-11eb-9100-40c792cb5c4e.png">
<img width="431" alt="Screen Shot 2021-03-29 at 8 25 06 PM" src="https://user-images.githubusercontent.com/32850517/112915707-e387fb80-90cc-11eb-97ef-f4da2bd26aa2.png">

Can protobuff decode my custom structures without knowing them ? Should I create a proto myself ?

Thanks for any help or nudge!

**Comment by fosteman** [comment]
Here's what I tried to do:
<img width="705" alt="Screen Shot 2021-03-30 at 1 41 22 PM" src="https://user-images.githubusercontent.com/32850517/113032237-9f910700-915d-11eb-81e0-ad4875e84a01.png">
Output: (empty payload)
<img width="662" alt="Screen Shot 2021-03-30 at 1 41 45 PM" src="https://user-images.githubusercontent.com/32850517/113032284-addf2300-915d-11eb-8c66-d3c6c47d3ea9.png">

Only `Struct` payload test:
<img width="586" alt="Screen Shot 2021-03-30 at 1 40 34 PM" src="https://user-images.githubusercontent.com/32850517/113032139-81c3a200-915d-11eb-8a49-c12e693ee685.png">
Output with missing values:
<img width="503" alt="Screen Shot 2021-03-30 at 1 40 45 PM" src="https://user-images.githubusercontent.com/32850517/113032159-88eab000-915d-11eb-8bd9-480fd742aac9.png">

Anything wrong I'm doing ?

**Comment by fosteman** [comment]
Anyone here ?

**Comment by fosteman** [comment]
Just pinging, anyone here ? I need to figure it out, but protobuff documentation seems humongous. Can you guys at least point me in the right direction ?

**Comment by b-loved-dreamer** [comment]
Hi @fosteman — thank you for filing this issue. Are you setting/using ```{json: true, values: true}```? PR [1495](https://github.com/protobufjs/protobuf.js/pull/1495) has some details.

> So, while we're in 6.x, use {json: true, values: true} to make .toObject generate proper JSON representations for these types. In 7.x I plan to remove values and properly document json (and probably make it enabled by default - this needs to be discussed).

Please let me know if this helps.

**Comment by b-loved-dreamer** [comment]
Hi @alexander-fenster, wanted to tag you in. I know you've been working on related fixes.

**Comment by fosteman** [comment]
> Hi @fosteman — thank you for filing this issue. Are you setting/using `{json: true, values: true}`?
> Please let me know if this helps.
Thanks for this tip, I am running the latest version, but the result came out exactly same with `{json: true, values: true}`

**Comment by alexander-fenster** [comment]
This is in progress. Currently, protobuf.js (the third-party library we use) has no support for proto3 JSON format, I'm working on making it support it. Unfortunately, switching to it will be a breaking change and a major version bump.

**Comment by telpirion** [comment]
Hello @fosteman , we have a workaround for working with `protobuf.Value` objects that we implemented in the [`nodejs-ai-platform` client library](https://github.com/googleapis/nodejs-ai-platform/blob/master/src/value-converter.ts).  You might try a similar value converter function like such.

**Comment by telpirion** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by alexander-fenster** [comment]
For those who finds this issue, please consider using the new npm [package](https://www.npmjs.com/package/proto3-json-serializer) we just released to convert to/from proto3 JSON.

```sh
npm install proto3-json-serializer
```
