### ISSUE TITLE
Support for Enable DTMF Settings

### ISSUE THREAD

**Issue by bivas6** [googleapis/nodejs-dialogflow-cx#98]
Hi,

In the CX UI user can define if the bot accept DTMF input in the current state.
This is not reflected in the bot response. I know that for CCAI clients SDK, the bot response do contains this information.

I would appreciate it if you could reflect this info.

Thanks!

**Comment by telpirion** [comment]
Thank you for providing this feature request for the Dialogflow service. Please file your feature request here on the [public issue tracker](https://issuetracker.google.com/issues/new?component=501190).
